name: Local Build and Postman Tests

on:
  workflow_dispatch:
    inputs:
      Query:
        description: 'Parameter for API request'
        required: true
        default: 'The+Rookie'
        type: string
      Url:
        description: 'Parameter for API request'
        required: false
        default: 'http://127.0.0.1:8443'
        type: choice
        options:
          - 'http://127.0.0.1:8443'
          - 'https://torapi.vercel.app'
          - 'https://toruapi.vercel.app'
          - 'https://rutorapi.vercel.app'
      Iterations:
        description: 'Iteration count for tests'
        required: true
        default: 1
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    # - name: Install Node.js
    #   run: |
    #     sudo apt update
    #     curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
    #     sudo apt-get install -y nodejs
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Packet check
      run: |
        echo "node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "newman version: $(newman --version)"

    - name: Install dependencies
      run: |
        npm install

    - name: Start local server
      run: |
        npm start > torapi.log &

    - name: Run postman tests
      run: |
        newman run postman-tests.json \
        --env-var "query=${{ github.event.inputs.Query }}" \
        --env-var "baseUrl=${{ github.event.inputs.Url }}" \
        --iteration-count ${{ github.event.inputs.Iterations }} \
        --reporters cli,junit,html \
        --reporter-html-export postman-report.html \
        --reporter-junit-export postman-results.xml

    - name: View log
      run: |
        cat torapi.log

    - name: Upload Newman HTML Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Postman HTML Report
        path: postman-report.html

    - name: Publish JUnit Test Results
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/postman-results.xml'