name: Local Build and Postman Tests

on:
  workflow_dispatch:
    inputs:
      Query:
        description: 'Parameter for API request'
        required: true
        default: 'The Rookie'
        type: string
      Iterations:
        description: 'Iteration count for tests'
        required: false
        default: 1
        type: number
      Url:
        description: 'Local or Publish server'
        required: false
        default: 'http://localhost:8443'
        type: choice
        options:
          - 'http://localhost:8443'
          - 'https://torapi.vercel.app'
          - 'https://toruapi.vercel.app'
          - 'https://rutorapi.vercel.app'
      Docker:
        description: 'Build docker image'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Packet check
      run: |
        echo "node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "newman version: $(newman --version)"

    - name: Build docker image and run container
      if: ${{ github.event.inputs.Url == 'http://localhost:8443' && github.event.inputs.Docker == 'true' }}
      run: |
        docker build -t lifailon/torapi:latest .
        docker run -d --name TorAPI -p 8443:8443 lifailon/torapi:latest
        for i in {1..10}; do
          response_code=$(curl -o /dev/null -s -w '%{http_code}' http://localhost:8443/api/provider/list 2> /dev/null || echo "404") 
          if [ "$response_code" -eq 200 ]; then
            echo "Server is up (status code 200)"
            break
          else
            echo "Waiting for the server to start: $(($i*5)) seconds..."
            sleep 5
          fi
        done

    - name: Install dependencies and start local server
      if: ${{ github.event.inputs.Url == 'http://localhost:8443' && github.event.inputs.Docker == 'false' }}
      run: |
        npm install
        npm start > torapi.log &

    - name: Run postman tests
      run: |
        newman run postman-tests.json \
        --env-var "query=${{ github.event.inputs.Query }}" \
        --env-var "baseUrl=${{ github.event.inputs.Url }}" \
        --iteration-count ${{ github.event.inputs.Iterations }} \
        --reporters cli,junit,html \
        --reporter-html-export postman-report.html \
        --reporter-junit-export postman-results.xml

    - name: View local server logs
      if: ${{ github.event.inputs.Url == 'http://localhost:8443' && (success() || failure()) }}
      run: |
        if [ "${{ github.event.inputs.Docker }}" = "false" ]; then
          cat torapi.log
        else
          docker logs TorAPI
        fi

    - name: Upload Newman HTML Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Postman HTML Report
        path: postman-report.html

    - name: Publish JUnit Test Results
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/postman-results.xml'