name: Local Build and Postman Tests

on:
  workflow_dispatch:
    inputs:
      Query:
        description: 'Parameter for API request'
        required: true
        default: 'The+Rookie'
        type: string
      Iterations:
        description: 'Iteration count for tests'
        required: true
        default: 1
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    # - name: Install Node.js
    #   run: |
    #     sudo apt update
    #     curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
    #     sudo apt-get install -y nodejs
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Packet check
      run: |
        echo "node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "newman version: $(newman --version)"

    - name: Run postman tests
      run: |
        newman run postman-tests.json \
        --iteration-count ${{ github.event.inputs.Iterations }} \
        --env-var "query=${{ github.event.inputs.Query }}" \
        --reporters cli,junit,html \
        --reporter-html-export newman-report.html \
        --reporter-junit-export newman-results.xml

    - name: Upload Newman Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: newman-results
        path: newman-results.xml

    - name: Upload Newman HTML Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: newman-html-report
        path: newman-report.html

    - name: Publish JUnit Test Results
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/newman-results.xml'